### ISSUE TITLE
Error at the last step of installation

### ISSUE THREAD

**Issue by michaeledbert** [JackieZhai/SiamBOMB#1]
(SiamBOMB) C:\Windows\System32\SiamBOMB>python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    ext_modules=cythonize(ext_modules)
  File "C:\Users\USER\anaconda3\envs\SiamBOMB\lib\site-packages\Cython\Build\Dependencies.py", line 972, in cythonize
    aliases=aliases)
  File "C:\Users\USER\anaconda3\envs\SiamBOMB\lib\site-packages\Cython\Build\Dependencies.py", line 815, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\Users\USER\anaconda3\envs\SiamBOMB\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: 'toolkit/utils/region.pyx' doesn't match any files

**Comment by michaeledbert** [comment]
Hello, @JackieZhai I want to try to install the SiamBOMB. But however, at the last step of the installation, I met with this error notification. Could you help me to get through this problem? Thanks before.

**Comment by JackieZhai** [comment]
Sorry about missing the folder "toolkit". But now, we have updated, so you can try it again. Hope to help you.
